### ISSUE TITLE
Diagrama / algoritmo dataset

### ISSUE THREAD

**Issue by thiagopx** [thiagopx/cayo_tcc#1]

**Comment by cayodonatti** [comment]
Esboço:
http://i.imgur.com/mCLJpfx.png

**Comment by cayodonatti** [comment]
Os dados utilizados nesse trabalho foram extraídos do site www.cifraclub.com.br utilizando técnicas de rastreamento Web (Web crawling, em inglês). Foram extraídas, ao todo, 66 mil cifras, divididas entre 72 gêneros musicais.
Web Crawling é definido por Castillo como "o processo utilizado por motores de busca para coletar paginas da Internet". 
Após a obtenção das páginas necessárias, ocorreram sucessivas análises e buscas nestas, para obtermos e extrairmos as informação necessárias. Para tal, foram utilizadas técnicas de programação envolvendo filtragem de conteúdo HTML através de expressões XPath.
Xpath ou XML Path Language é uma tecnologia utilizada para se obter partes específicas endereçadas em documentos XML.


Referências: 
Castillo, Carlos. "Effective web crawling." Acm sigir forum. Vol. 39. No. 1. Acm, 2005.
Berglund, Anders, et al. "Xml path language (xpath)." World Wide Web Consortium (W3C) (2003).

**Comment by thiagopx** [comment]
- 66 mil é o número exato?

**Comment by cayodonatti** [comment]
66051

**Comment by cayodonatti** [comment]
Motivo da escolha do CifraClub:
Foi escolhido o CifraClub pelo fato de este ser o site de ensino de música mais acessado no Brasil, com 403 mil músicas e 7.6 milhões de pessoas cadastradas.
Fonte: Studio Sol, desenvolvedores do CifraClub em https://www.studiosol.com.br/cifraclub
