### ISSUE TITLE
Objetivos

### ISSUE THREAD

**Issue by thiagopx** [thiagopx/cayo_tcc#2]

**Comment by thiagopx** [comment]
- Busca exata / aproximada por sequência de acordes.
- Recomendação de sequência harmônica baseada  em dados.
- Recomendação de músicas com base em sequências harmônicas.

**Comment by cayodonatti** [comment]
Esboço inicial:
O objetivo principal deste trabalho é implementar um sistema de busca por sequência de acordes em uma base de dados de músicas. Tal busca será implementada a partir de duas formas de algoritmo: busca exata, que é feita à partir de uma sequência de acordes definidos, e busca aproximada, que busca por sequências semelhantes à informada pelo usuário do sistema.
À partir desses algoritmos de busca, será implementado um algoritmo de recomendação de músicas que, diferente da teoria musical que se baseia em sequências harmônicas, fará recomendações de músicas baseando-se nos dados de sequências harmônicas disponíveis. O caminho oposto também será possível, ou seja, recomendação de músicas com base nas sequências harmônicas (novamente, baseando-se em dados ao invés de teoria musical).

**Comment by cayodonatti** [comment]
V2 com revisão da Isaura:

O objetivo geral consiste em implementar um sistema de busca por sequência de acordes em uma base de dados de músicas. Tal busca será implementada a partir de duas formas de algoritmos: o de busca exata, a partir de uma sequência de acordes definidos, e o de busca aproximada, a partir de sequências com algum grau definido de similaridade à informada pelo usuário.
Com base nesses algoritmos de busca, será implementado um algoritmo de recomendação de músicas que fará recomendações baseando-se nos dados de sequências harmônicas disponíveis, relacionando-as com músicas selecionadas na base pelo usuário. Tal abordagem difere da teoria musical que se baseia em campos harmônicos. 
O algoritmo também deverá ser capaz de recomendar músicas com base em sequências harmônicas definidas pelo usuário (novamente, baseando-se em dados ao invés de teoria musical).
Objetivos Específicos:
- Identificar possíveis base de dados de músicas a partir da web e selecionar uma deles para o trabalho;
- Selecionar um modelo de busca aproximada para o algoritmo de recomendação;
- Selecionar um modelo de dados que favoreçam a análise pelos algoritmos de busca simples e de recomendação;

**Comment by thiagopx** [comment]
Recomendação de música, a princípio, está fora do escopo de trabalho.

- Busca exata / aproximada por um progressão de acordes.
- Sugestão de progressões baseada em dados.

**Comment by cayodonatti** [comment]
V3:
O objetivo geral consiste em implementar um sistema de busca por sequência de acordes em uma base de dados de músicas. Tal busca será implementada a partir de duas formas de algoritmos: o de busca exata, a partir de uma sequência de acordes definidos, e o de busca aproximada, a partir de sequências com algum grau definido de similaridade à informada pelo usuário.
Com base nesses algoritmos de busca, será implementado um algoritmo de levantamento de músicas que fará indicações baseando-se nos dados de sequências harmônicas disponíveis, relacionando-as com músicas selecionadas na base pelo usuário. Tal abordagem difere da teoria musical que se baseia em campos harmônicos. 
O algoritmo também deverá ser capaz de identificar músicas com base em sequências harmônicas definidas pelo usuário (novamente, baseando-se em dados ao invés de teoria musical).
Objetivos Específicos:
- Identificar possíveis base de dados de músicas a partir da web e selecionar uma deles para o trabalho;
- Selecionar um modelo de busca aproximada para o algoritmo de identificação;
- Selecionar um modelo de dados que favoreçam a análise pelos algoritmos de busca simples e de identificação..
