### ISSUE TITLE
Implementação modelo de representação musical baseado em distâncias

### ISSUE THREAD

**Issue by thiagopx** [thiagopx/cayo_tcc#6]

**Comment by thiagopx** [comment]
Escrever sobre o modelo no formato do relatório

**Comment by cayodonatti** [comment]
Primeiro modelo de queries para o Neo4j:

CREATE (master: Music {name: "Master of Puppets"})
CREATE (metallica: Artist {name: "Metallica"})
CREATE (metal: Genre {name: "Metal"})
CREATE (c: Chord {name: "C", C: 1, C#: 0, D: 0, D#: 0, E: 1, F: 0, F#: 0, G: 1, G#: 0, A: 0, A#: 0, B: 0]})
CREATE (g) -[:SEQUENCE_OF {distance: 0.7}] -> (c)
CREATE (c) -[:CHORD_OF {position: 0}] -> (rumine)


MATCH (chordA: Chord {name: "C"})
MATCH (chordB: Chord {name: "G"})
MATCH (chordB) - [sequence: SEQUENCE_OF] -> (chordA)
RETURN sequence.distance as Distancia


MATCH (chordA: Chord) -[CHORD_OF {position: 0}]-> (Music {name: "Master of Puppets"})
MATCH (chordB: Chord) -[CHORD_OF {position: 1}]-> (Music {name: "Master of Puppets"})
MATCH (chordB) - [sequence: SEQUENCE_OF] -> (chordA)
RETURN sequence.distance as Distancia

**Comment by cayodonatti** [comment]
Vantagens desse modelo:
- Só precisamos transformar o acordo para o vetor de bytes uma vez, depois disso podemos buscá-lo no banco, o que é bem mais rápido;
- Só precisamos calcular a distância uma vez para cada transição, o que também aumenta a performance;

PS: ainda não testei essas queries, eu fiz esse modelo baseando-se nos tutoriais do Neo4j. Chegando em casa eu faço alguns testes para ver se tudo vai funcionar conforme esperado
